apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: frontend
  description: frontend dev team
spec:
  type: team
  profile:
    displayName: Frontend Team
    picture: https://acme-corp-images.s3.eu-south-2.amazonaws.com/dev-logo.jpg
  parent: dev
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: roadrunner
spec:
  profile:
    displayName: Roadrunner
    email: roadrunner@acme-corp.com
    picture: https://acme-corp-images.s3.eu-south-2.amazonaws.com/roadrunner.png
  memberOf: [frontend]